### ISSUE TITLE
PRs from Alpine packaging activity

### ISSUE THREAD

**Issue by jswank** [johnsonjh/OpenVi#29]
I've been working on a Alpine package for this editor.  I just submitted a few PRs around some aspects of the install target in the GNUmakefile to make that go a bit smoother.  They are all independent, but I'm happy to mix and match them based on your preference.

Thanks for making this version of vi available: I've been enjoying it!

**Comment by johnsonjh** [comment]
@jswank 

Thank you for your contributions.

I've merged your pull requests (with slight modifications to spacing only) to master.  As I'm working on my phone right now, I've not extensively tested the installation changes yet, and hopefully didn't break anything.  Let me know if this is helpful for your Alpine packaging, or if there is anything else you need.  Also, if you want to be credited in the ChangeLog in a different way, please advise. 

In the near future, I am considering switching to using `install` for installing binaries, specifically, the enhanced OpenBSD-derived [xinstall](https://github.com/johnsonjh/OpenVi/tree/master/xinstall) version in the source tree, so you might want to try it out and see if it has any issues.

**Comment by lobre** [comment]
It seems the package is now available in Alpine.

https://pkgs.alpinelinux.org/packages?name=openvi&branch=edge&repo=&arch=&maintainer=

Does this issue still make sense?

**Comment by johnsonjh** [comment]
@lobre Thanks for the update - I'll close this as completed =)
