### ISSUE TITLE
Expandtab/shell command related issue

### ISSUE THREAD

**Issue by danielcanencia** [johnsonjh/OpenVi#34]
Whenever a shell command is executed via the ex command '!', and only when the option expandtab is set, vi reports Error: unable to retrieve line 0. 

The next screenshot shows the ouput of the !ls command before and after setting the expandtab option.

![2023-11-13-173418_944x245_scrot](https://github.com/johnsonjh/OpenVi/assets/71571286/b9ba06e6-0d22-44aa-86d2-05df27944d21)

**Comment by johnsonjh** [comment]
Confirmed. Spooky.

**Comment by johnsonjh** [comment]
A proper/better coming fix soon; but committing a workaround to master which will suppress the spurious message in this, and possibly a few other cases.
